services:
  ptool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ptool
    volumes:
      - ./config:/config
    environment:
      - TZ=America/New_York
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
